# Generated by Django 2.1.5 on 2019-03-18 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, null=True)),
                ('path', models.TextField(db_index=True, max_length=256, null=True)),
                ('ext', models.TextField(max_length=32, null=True)),
                ('binary', models.BooleanField(default=False)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, null=True)),
                ('path', models.TextField(db_index=True, max_length=256, null=True)),
                ('ext', models.TextField(max_length=32)),
                ('binary', models.BooleanField(default=False)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDay', models.DateTimeField(null=True)),
                ('interval', models.TextField(choices=[('DY', 'day'), ('WK', 'week'), ('MN', 'month')], max_length=5)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='repos',
        ),
        migrations.AddField(
            model_name='commit',
            name='subject',
            field=models.TextField(db_index=True, default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srcOptics.Organization'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.TextField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.TextField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.TextField(max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='srcOptics.Author'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='srcOptics.File'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='srcOptics.Repository'),
        ),
        migrations.AddField(
            model_name='filechange',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='srcOptics.Commit'),
        ),
        migrations.AddField(
            model_name='filechange',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filechange_repo', to='srcOptics.Repository'),
        ),
        migrations.AddField(
            model_name='file',
            name='changes',
            field=models.ManyToManyField(related_name='changes', to='srcOptics.FileChange'),
        ),
        migrations.AddField(
            model_name='file',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_repo', to='srcOptics.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='files',
            field=models.ManyToManyField(to='srcOptics.File'),
        ),
    ]
