# Generated by Django 2.1.5 on 2019-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author_date',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='commit_date',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
