# Generated by Django 2.1.4 on 2019-02-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='repos',
        ),
        migrations.AddField(
            model_name='repository',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='srcOptics.Organization'),
        ),
    ]
