# Generated by Django 2.2 on 2019-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('start_date', 'interval', 'repo', 'author', 'file')},
        ),
    ]
