# Generated by Django 2.1.4 on 2019-01-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='', max_length=32)),
                ('password', models.TextField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='account',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='srcOptics.Account'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='members', to='srcOptics.Account'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.TextField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcOptics.Repository'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='logincredential',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcOptics.Repository'),
        ),
        migrations.AddField(
            model_name='author',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcOptics.Commit'),
        ),
    ]
