# Generated by Django 2.1.5 on 2019-02-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0002_auto_20190211_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
