# Generated by Django 2.1.5 on 2019-02-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0002_auto_20190211_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srcOptics.Commit')),
            ],
        ),
    ]
