# Generated by Django 2.2 on 2019-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0002_auto_20190518_0024'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistic',
            name='total_rollup',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='total_rollup_brin',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup_brin',
        ),
    ]
