# Generated by Django 2.1.4 on 2019-01-30 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0002_auto_20190128_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='account',
            name='repos',
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
