# Generated by Django 2.1.5 on 2019-02-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0003_auto_20190217_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
