# Generated by Django 2.2 on 2019-05-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0003_auto_20190518_0031'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_commit__abe930_idx',
        ),
        migrations.AddField(
            model_name='repository',
            name='last_rollup',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'author'], name='srcOptics_c_commit__d99f63_idx'),
        ),
    ]
