# Generated by Django 2.0.10 on 2019-04-15 15:18

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0003_repository_last_pulled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logincredential',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logincredential',
            name='name',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='earliest_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='interval',
            field=models.TextField(choices=[('DY', 'Day'), ('WK', 'Week'), ('MN', 'Month')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='start_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'repo'], name='srcOptics_c_commit__abe930_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'author'], name='srcOptics_c_commit__d99f63_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['lines_added', 'lines_removed'], name='srcOptics_c_lines_a_8ddab5_brin'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo'], name='total_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['interval', 'lines_added', 'lines_removed', 'lines_changed', 'commit_total', 'files_changed', 'author_total'], name='srcOptics_s_interva_275c43_brin'),
        ),
        migrations.AddField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='tagged_repos', to='srcOptics.Repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='srcOptics.Tag'),
        ),
    ]
