# Generated by Django 2.1.5 on 2019-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0004_auto_20190415_1518'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_commit__d99f63_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_lines_a_8ddab5_brin',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='srcOptics_s_interva_275c43_brin',
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'author', 'repo'], name='srcOptics_c_commit__6b90b4_idx'),
        ),
    ]
