# Generated by Django 2.0.10 on 2019-03-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0004_auto_20190327_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredential',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logincredential',
            name='name',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='attributes',
            field=models.TextField(choices=[('commit_total', 'Total Commits'), ('lines_added', 'Lines Added'), ('lines_removed', 'Lines Removed'), ('lines_changed', 'Lines Changed'), ('files_changed', 'Files Changed'), ('author_total', 'Total Authors')], default='', max_length=24),
            preserve_default=False,
        ),
    ]
