# Generated by Django 2.0.10 on 2019-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0004_auto_20190320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
