# Generated by Django 2.0.10 on 2019-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0004_auto_20190327_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredential',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='logincredential',
            name='name',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
