# Generated by Django 2.0.10 on 2019-02-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0004_auto_20190130_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='commit',
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='srcOptics.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='srcOptics.Repository'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='password',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='username',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orgs', to='srcOptics.Organization'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.TextField(max_length=256),
        ),
    ]
