# Generated by Django 2.1.5 on 2019-02-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0003_filechange'),
        ('srcOptics', '0005_auto_20190217_1917'),
    ]

    operations = [
    ]
