# Generated by Django 2.0.10 on 2019-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0005_auto_20190329_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='attributes',
        ),
    ]
