# Generated by Django 2.0.10 on 2019-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0005_auto_20190328_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logincredential',
            name='description',
        ),
        migrations.RemoveField(
            model_name='logincredential',
            name='name',
        ),
    ]
