# Generated by Django 2.2 on 2019-05-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0005_auto_20190518_0245'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_commit__d99f63_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_commit__abe930_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='rollup2',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='rollup3',
        ),
    ]
