# Generated by Django 2.0.10 on 2019-04-24 19:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0005_auto_20190417_1528'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistic',
            name='total_rollup',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup',
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo'], name='total_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup'),
        ),
    ]
