# Generated by Django 2.1.5 on 2019-03-27 15:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0006_auto_20190323_1627'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_repo_id_09963b_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='srcOptics_c_author__8a3d7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='srcOptics_s_interva_cb775a_idx',
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='interval',
            field=models.TextField(choices=[('DY', 'day'), ('WK', 'week'), ('MN', 'month')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='start_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'repo'], name='srcOptics_c_commit__abe930_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'author'], name='srcOptics_c_commit__d99f63_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['lines_added', 'lines_removed'], name='srcOptics_c_lines_a_8ddab5_brin'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo'], name='total_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['interval', 'lines_added', 'lines_removed', 'lines_changed', 'commit_total', 'files_changed', 'author_total'], name='srcOptics_s_interva_275c43_brin'),
        ),
    ]
