# Generated by Django 2.1.5 on 2019-02-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0006_merge_20190217_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='subject',
            field=models.TextField(default='subject', max_length=256),
            preserve_default=False,
        ),
    ]
