# Generated by Django 2.0.10 on 2019-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0006_remove_statistic_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=64, null=True)),
                ('repos', models.ManyToManyField(related_name='tagged_repos', to='srcOptics.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='srcOptics.Tag'),
        ),
    ]
