# Generated by Django 2.0.10 on 2019-04-24 19:25

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0006_auto_20190424_1919'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistic',
            name='total_rollup',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup',
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo'], name='total_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo'], name='total_rollup_brin'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup_brin'),
        ),
    ]
