# Generated by Django 2.2 on 2019-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0006_auto_20190518_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
