# Generated by Django 2.0.10 on 2019-03-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0007_auto_20190329_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='srcOptics.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='tagged_repos', to='srcOptics.Repository'),
        ),
    ]
