# Generated by Django 2.0.10 on 2019-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0007_auto_20190328_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='logincredential',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logincredential',
            name='name',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
