# Generated by Django 2.1.5 on 2019-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0007_commit_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='binary',
            field=models.BooleanField(default=False),
        ),
    ]
