# Generated by Django 2.1.5 on 2019-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0008_filechange_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='ext',
            field=models.TextField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
