# Generated by Django 2.0.10 on 2019-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0008_auto_20190328_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='attributes',
            field=models.TextField(choices=[('commit_total', 'Total Commits'), ('lines_added', 'Lines Added')], default='', max_length=24),
            preserve_default=False,
        ),
    ]
