# Generated by Django 2.0.10 on 2019-03-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0010_auto_20190328_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='attributes',
            field=models.TextField(choices=[('commit_total', 'Total Commits'), ('lines_added', 'Lines Added'), ('lines_removed', 'Lines Removed'), ('lines_changed', 'Lines Changed'), ('files_changed', 'Files Changed'), ('author_total', 'Total Authors')], max_length=24),
        ),
    ]
