# Generated by Django 2.0.10 on 2019-02-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0010_auto_20190218_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='srcOptics.Repository'),
        ),
    ]
