# Generated by Django 2.0.10 on 2019-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0010_auto_20190401_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='tagged_repos', to='srcOptics.Repository'),
        ),
    ]
