# Generated by Django 2.0.10 on 2019-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0011_auto_20190401_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
