# Generated by Django 2.1.5 on 2019-02-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0011_filechange_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, null=True)),
                ('path', models.TextField(db_index=True, max_length=256, null=True)),
                ('ext', models.TextField(max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.TextField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='files',
            field=models.ManyToManyField(related_name='files', to='srcOptics.File'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.TextField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='commit',
            name='subject',
            field=models.TextField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='name',
            field=models.TextField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='path',
            field=models.TextField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filechange_repo', to='srcOptics.Repository'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='file',
            name='changes',
            field=models.ManyToManyField(related_name='changes', to='srcOptics.FileChange'),
        ),
        migrations.AddField(
            model_name='file',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_repo', to='srcOptics.Repository'),
        ),
    ]
