# Generated by Django 2.0.10 on 2019-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0012_auto_20190401_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='earliest_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
