# Generated by Django 2.1.5 on 2019-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0012_auto_20190218_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='files',
            field=models.ManyToManyField(to='srcOptics.File'),
        ),
    ]
