# Generated by Django 2.1.5 on 2019-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0013_auto_20190218_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lines_added',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='lines_removed',
            field=models.IntegerField(default=0),
        ),
    ]
