# Generated by Django 2.0.10 on 2019-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0014_auto_20190411_2056'),
        ('srcOptics', '0014_auto_20190410_2134'),
    ]

    operations = [
    ]
