# Generated by Django 2.1.5 on 2019-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0014_auto_20190218_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='binary',
            field=models.BooleanField(default=False),
        ),
    ]
