# Generated by Django 2.1.5 on 2019-02-19 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0015_file_binary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDay', models.DateTimeField(null=True)),
                ('interval', models.TextField(choices=[('DY', 'day'), ('WK', 'week'), ('MN', 'month')], max_length=5)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='srcOptics.Author')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='srcOptics.File')),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='srcOptics.Repository')),
            ],
        ),
    ]
