# Generated by Django 2.0.10 on 2019-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0016_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='lastScanned',
            field=models.DateTimeField(null=True),
        ),
    ]
