# Generated by Django 2.0.10 on 2019-02-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0017_auto_20190222_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='lastScanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
