# Generated by Django 2.0.10 on 2019-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0018_auto_20190222_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='password',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
