# Generated by Django 2.0.10 on 2019-02-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0019_auto_20190222_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincredential',
            name='username',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='repository',
            name='cred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srcOptics.LoginCredential'),
        ),
    ]
