# Generated by Django 2.0.10 on 2019-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0020_auto_20190224_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(blank=True, db_index=True, max_length=32),
        ),
    ]
