# Generated by Django 2.0.10 on 2019-02-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0021_auto_20190224_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='lastScanned',
            new_name='last_scanned',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='startDay',
            new_name='start_date',
        ),
    ]
