# Generated by Django 2.1.5 on 2019-03-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0022_auto_20190227_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='repos',
            field=models.ManyToManyField(to='srcOptics.Repository'),
        ),
    ]
