# Generated by Django 2.1.5 on 2019-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0023_author_repos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='repos',
            field=models.ManyToManyField(related_name='author_repos', to='srcOptics.Repository'),
        ),
    ]
