# Generated by Django 2.0.10 on 2019-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcOptics', '0024_auto_20190301_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='data',
        ),
        migrations.AddField(
            model_name='statistic',
            name='author_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='commit_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='files_changed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='lines_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='lines_changed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='lines_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
