# Generated by Django 2.2.1 on 2019-07-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logincredential',
            options={'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AddField(
            model_name='logincredential',
            name='ssh_private_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='logincredential',
            name='ssh_unlock_passphrase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='repos',
            field=models.ManyToManyField(related_name='_author_repos_+', to='source_optics.Repository'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='source_optics.Author'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='source_optics.Repository'),
        ),
        migrations.AlterField(
            model_name='file',
            name='changes',
            field=models.ManyToManyField(related_name='_file_changes_+', to='source_optics.FileChange'),
        ),
        migrations.AlterField(
            model_name='file',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='source_optics.Repository'),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='source_optics.Repository'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='password',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='username',
            field=models.TextField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='_organization_admins_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='_organization_members_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='_tag_repos_+', to='source_optics.Repository'),
        ),
    ]
