# Generated by Django 2.2.2 on 2019-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0001_squashed_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='days_before_last',
        ),
        migrations.AddField(
            model_name='statistic',
            name='commits_per_day',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='files_changed_per_day',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='lines_changed_per_day',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
