# Generated by Django 2.2.2 on 2019-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0002_auto_20190903_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='bias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='flux',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
