# Generated by Django 2.2.2 on 2019-09-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0003_auto_20190903_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='commitment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
