# Generated by Django 2.2.2 on 2019-07-22 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0003_auto_20190722_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('username', models.TextField(blank=True, help_text='github/gitlab username', max_length=32)),
                ('password', models.TextField(blank=True, help_text='github/gitlab password (if using API imports)', max_length=128, null=True)),
                ('ssh_private_key', models.TextField(blank=True, help_text='for cloning private repos', null=True)),
                ('ssh_unlock_passphrase', models.TextField(blank=True, help_text='for cloning private repos', null=True)),
                ('description', models.TextField(blank=True, max_length=128, null=True)),
                ('api_endpoint', models.TextField(blank=True, help_text='optional git hosting API endpoint for import commands', null=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.RemoveField(
            model_name='repository',
            name='cred',
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(help_text='currently unused', related_name='_organization_admins_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(help_text='currently unused', related_name='_organization_members_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='enabled',
            field=models.BooleanField(default=True, help_text='if false, disable scanning'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.TextField(help_text='use a git ssh url for private repos, else http/s are ok', max_length=256, unique=True),
        ),
        migrations.DeleteModel(
            name='LoginCredential',
        ),
        migrations.AddField(
            model_name='organization',
            name='credential',
            field=models.ForeignKey(help_text='used for repo imports and git checkouts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='source_optics.Credential'),
        ),
    ]
