# Generated by Django 2.2.2 on 2019-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0004_auto_20190722_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='import_filter',
            field=models.CharField(blank=True, help_text='if set, only import repos matching this fnmatch pattern', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='organization_identifier',
            field=models.CharField(blank=True, help_text='for github/gitlab imports', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='api_endpoint',
            field=models.TextField(blank=True, help_text='for github/gitlab imports off private instances', null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.TextField(blank=True, help_text='for github/gitlab imports', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.TextField(blank=True, help_text='for github/gitlab username', max_length=32),
        ),
    ]
