# Generated by Django 2.2.2 on 2019-09-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0006_file_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(db_index=True, max_length=512, null=True, unique=True)),
                ('to_email', models.CharField(db_index=True, max_length=512, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='source_optics.Organization')),
            ],
            options={
                'verbose_name_plural': 'EmailAliases',
            },
        ),
    ]
