# Generated by Django 2.2.2 on 2019-07-23 15:08

from django.db import migrations, models
import source_optics.models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0006_auto_20190723_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='checkout_path_override',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(db_index=True, max_length=32, validators=[source_optics.models.validate_repo_name]),
        ),
    ]
