# Generated by Django 2.2.2 on 2019-07-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0007_auto_20190723_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='force_nuclear_rescan',
            field=models.BooleanField(default=False, help_text='on next scan loop, delete all commits/records and rescan everything'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='force_next_pull',
            field=models.BooleanField(default=False, help_text='used by webhooks to signal the scanner'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='prevents against trivial webhook spam', max_length=255, null=True),
        ),
    ]
