# Generated by Django 2.2.2 on 2019-09-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0007_auto_20190913_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalias',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='source_optics.Organization'),
        ),
    ]
