# Generated by Django 2.2.2 on 2019-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0008_auto_20190723_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='scanner_directory_allow_list',
            field=models.TextField(blank=True, help_text='if set, fnmatch patterns of directories to require, one per line', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='scanner_directory_deny_list',
            field=models.TextField(blank=True, help_text='fnmatch patterns or prefixes of directories to exclude, one per line', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='scanner_extension_allow_list',
            field=models.TextField(blank=True, help_text='if set, fnmatch patterns of extensions to require, one per line', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='scanner_extension_deny_list',
            field=models.TextField(blank=True, help_text='fnmatch patterns or prefixes of extensions to exclude, one per line ', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='checkout_path_override',
            field=models.CharField(blank=True, help_text='if set, override the default checkout location', max_length=512, null=True),
        ),
    ]
