# Generated by Django 2.2.2 on 2019-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0009_auto_20190724_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='scanner_directory_allow_list',
            field=models.TextField(blank=True, help_text='if set, fnmatch patterns of directories to require, one per line', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='scanner_directory_deny_list',
            field=models.TextField(blank=True, help_text='fnmatch patterns or prefixes of directories to exclude, one per line', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='scanner_extension_allow_list',
            field=models.TextField(blank=True, help_text='if set, fnmatch patterns of extensions to require, one per line', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='scanner_extension_deny_list',
            field=models.TextField(blank=True, help_text='fnmatch patterns or prefixes of extensions to exclude, one per line ', null=True),
        ),
    ]
