# Generated by Django 2.2.5 on 2019-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0009_auto_20190918_1006'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup2',
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup3'),
        ),
    ]
