# Generated by Django 2.2.5 on 2019-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0010_auto_20190918_1434'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='commit1',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit2',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='file1',
        ),
        migrations.RemoveIndex(
            model_name='filechange',
            name='file_change1',
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date', 'author', 'repo'], name='commit1'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['author_date', 'author', 'repo'], name='commit2'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['repo', 'name', 'path'], name='file2'),
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=models.Index(fields=['file', 'commit'], name='file_change2'),
        ),
    ]
