# Generated by Django 2.2.2 on 2019-07-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0011_auto_20190725_2025'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='statistic',
            name='rollup1',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='earliest_commit',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='last_rollup',
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('start_date', 'interval', 'repo', 'author')},
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='file',
        ),
    ]
