# Generated by Django 2.2.5 on 2019-09-18 22:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0012_auto_20190918_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit1',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit2',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit3',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit4',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit5',
        ),
        migrations.RemoveIndex(
            model_name='emailalias',
            name='email_alias1',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='file2',
        ),
        migrations.RemoveIndex(
            model_name='filechange',
            name='file_change2',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='source_opti_organiz_45e49d_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup3',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup4',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup5',
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['commit_date', 'author', 'repo'], name='commit1'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['author_date', 'author', 'repo'], name='commit2'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['repo', 'name', 'path'], name='file1'),
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['file', 'commit'], name='file_change1'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup2'),
        ),
        migrations.AddField(
            model_name='tag',
            name='repos',
            field=models.ManyToManyField(blank=True, related_name='_tag_repos_+', to='source_optics.Repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='source_optics.Tag'),
        ),
    ]
