# Generated by Django 2.2.2 on 2019-07-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0013_auto_20190727_0015'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='source_opti_email_d3e229_idx',
        ),
    ]
