# Generated by Django 2.2.5 on 2019-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0013_auto_20190918_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='last_scanned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
