# Generated by Django 2.2.2 on 2019-07-27 00:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0014_auto_20190727_0024'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='source_opti_commit__69e2b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='source_opti_author__cbf24f_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistic',
            name='author_rollup',
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['commit_date', 'author', 'repo'], name='commit1'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['author_date', 'author', 'repo'], name='commit2'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'interval', 'repo', 'author'], name='author_rollup2'),
        ),
    ]
