# Generated by Django 2.2.5 on 2019-09-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0014_statistic_last_scanned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='last_scanned_date',
            new_name='last_scanned',
        ),
    ]
