# Generated by Django 2.2.5 on 2019-09-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0015_auto_20190918_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='repos',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='tags',
        ),
        migrations.AddField(
            model_name='author',
            name='alias_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_of', to='source_optics.Author'),
        ),
        migrations.DeleteModel(
            name='EmailAlias',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
