# Generated by Django 2.2.2 on 2019-07-27 01:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0015_auto_20190727_0056'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['repo', 'name', 'path'], name='file1'),
        ),
        migrations.AddIndex(
            model_name='filechange',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['file', 'commit'], name='file_change1'),
        ),
    ]
