# Generated by Django 2.2.2 on 2019-08-07 20:24

from django.db import migrations, models
import source_optics.models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0016_auto_20190727_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commit',
            name='subject',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='api_endpoint',
            field=models.CharField(blank=True, help_text='for github/gitlab imports off private instances', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='import_filter',
            field=models.CharField(blank=True, help_text='if set, only import repos matching this fnmatch pattern', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, help_text='for github/gitlab imports', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='ssh_unlock_passphrase',
            field=models.CharField(blank=True, help_text='for cloning private repos', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, help_text='for github/gitlab username', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(db_index=True, max_length=64, validators=[source_optics.models.validate_repo_name]),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(db_index=True, help_text='use a git ssh url for private repos, else http/s are ok', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
