# Generated by Django 2.2.2 on 2019-08-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0017_auto_20190807_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(db_index=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='commit',
            name='subject',
            field=models.TextField(db_index=True),
        ),
    ]
