# Generated by Django 2.2.2 on 2019-08-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0019_auto_20190830_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='days_before_joined',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
