# Generated by Django 2.2.2 on 2019-08-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0021_auto_20190831_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='days_before_last',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_changes', to='source_optics.File'),
        ),
    ]
