# Generated by Django 2.2.2 on 2019-08-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_optics', '0022_auto_20190831_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='average_commit_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
